[package]
name = "starknado_zk_2"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.2"
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.11.0" }

[cairo]
sierra-replace-ids = false

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
